/**
 * One-off backfill: re-case every stored name to match what the controllers now
 * write on insert.
 *
 *   node scripts/normalize_names.js                -- dry run, changes nothing
 *   node scripts/normalize_names.js --sql          -- print the UPDATE statements
 *   node scripts/normalize_names.js --apply        -- write the changes (asks first)
 *   node scripts/normalize_names.js --apply --yes  -- write without asking
 *
 * Run from the backend directory so dotenv finds .env.
 *
 * It imports the SAME utils/nameCase.js the controllers use, which is the whole
 * point: hand-written SQL would re-implement the rules and immediately drift from
 * them. Whatever this produces is exactly what a fresh insert would produce, and
 * --sql generates its statements from that same result rather than from a second
 * implementation.
 *
 * organizations.name is deliberately NOT touched.
 */
import 'dotenv/config';
import readline from 'readline';
import pool from '../config/db.js';
import { toPersonName, toCompanyName, toTitleText } from '../utils/nameCase.js';

const APPLY = process.argv.includes('--apply');
const YES   = process.argv.includes('--yes');
const SQL   = process.argv.includes('--sql');

const quote = (v) => "'" + String(v).replace(/\\/g, '\\\\').replace(/'/g, "''") + "'";

// table, primary key, column, transform, human label
const TARGETS = [
    ['employees',       'id', 'first_name',    toPersonName,  'Employee first name'],
    ['employees',       'id', 'last_name',     toPersonName,  'Employee last name'],
    ['employees',       'id', 'title',         toTitleText,   'Employee job title'],
    ['users',           'id', 'first_name',    toPersonName,  'User first name (HR / Accountant / Org Admin)'],
    ['users',           'id', 'last_name',     toPersonName,  'User last name (HR / Accountant / Org Admin)'],
    ['clients',         'id', 'client_name',   toCompanyName, 'Client company name'],
    ['client_contacts', 'id', 'contact_name',  toPersonName,  'Client contact name'],
    ['client_contacts', 'id', 'contact_title', toTitleText,   'Client contact title'],
    ['placements',      'id', 'job_title',     toTitleText,   'Placement job title'],
];

const conn = await pool.getConnection();
let grandTotal = 0;
let confirmed  = YES;
const plan = [];

if (SQL) {
    console.log('-- Generated by scripts/normalize_names.js --sql');
    console.log('-- organizations.name is intentionally excluded.');
    console.log('START TRANSACTION;\n');
} else {
    console.log(APPLY ? 'MODE: APPLY - changes will be written\n' : 'MODE: DRY RUN - nothing will be written\n');
}

for (const [table, pk, col, fn, label] of TARGETS) {
    const [rows] = await conn.query(
        `SELECT \`${pk}\` AS id, \`${col}\` AS v FROM \`${table}\`
         WHERE \`${col}\` IS NOT NULL AND \`${col}\` <> ''`);

    // Strict !== comparison in JS: MySQL's default collation is case-insensitive,
    // so a SQL <> would report every row as already correct.
    const diffs = rows
        .map(r => ({ id: r.id, from: r.v, to: fn(r.v) }))
        .filter(r => r.from !== r.to);

    plan.push({ table, col, label, total: rows.length, changes: diffs.length });
    grandTotal += diffs.length;

    if (SQL) {
        if (diffs.length) {
            console.log(`-- ${label}: ${diffs.length} row(s)`);
            for (const d of diffs) {
                console.log(`UPDATE \`${table}\` SET \`${col}\` = ${quote(d.to)} WHERE \`${pk}\` = ${quote(d.id)};  -- was ${quote(d.from)}`);
            }
            console.log('');
        }
        continue;
    }

    console.log(label);
    console.log(`  ${table}.${col}: ${diffs.length} of ${rows.length} row(s) differ`);
    for (const d of diffs.slice(0, 5)) console.log(`    ${JSON.stringify(d.from)}  ->  ${JSON.stringify(d.to)}`);
    if (diffs.length > 5) console.log(`    ... and ${diffs.length - 5} more`);
    console.log('');

    if (APPLY && diffs.length) {
        if (!confirmed) {
            const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
            const answer = await new Promise(r =>
                rl.question('Write these changes to the database? type yes to continue: ', a => { rl.close(); r(a); }));
            if (answer.trim().toLowerCase() !== 'yes') { console.log('Aborted, nothing written.'); conn.release(); process.exit(1); }
            confirmed = true;
        }
        await conn.beginTransaction();
        try {
            for (const d of diffs) {
                await conn.query(`UPDATE \`${table}\` SET \`${col}\` = ? WHERE \`${pk}\` = ?`, [d.to, d.id]);
            }
            await conn.commit();
            console.log(`  -> wrote ${diffs.length} row(s) to ${table}.${col}\n`);
        } catch (e) {
            await conn.rollback();
            console.error(`  -> FAILED, rolled back: ${e.message}\n`);
            throw e;
        }
    }
}

if (SQL) {
    console.log('COMMIT;');
    conn.release();
    process.exit(0);
}

console.log('-'.repeat(74));
console.log('SUMMARY');
for (const p of plan) {
    console.log(`  ${(p.table + '.' + p.col).padEnd(30)} ${String(p.changes).padStart(4)} / ${String(p.total).padEnd(5)} changed   ${p.label}`);
}
console.log(`  ${'TOTAL'.padEnd(30)} ${String(grandTotal).padStart(4)} row(s)`);
console.log('\n  organizations.name  - deliberately NOT changed');
if (!APPLY) console.log('\nRe-run with --apply to write these changes, or --sql to print them as SQL.');

conn.release();
process.exit(0);
